package god

import (
	"strings"
	"time"
)

// ShardRequest represents a prefetch shard request generated by the AA compiler.
type ShardRequest struct {
	Command string           `json:"command"`
	Args    ShardRequestArgs `json:"args"`
}

// ShardRequestArgs holds command-specific arguments for a shard request.
type ShardRequestArgs struct {
	MissionID string `json:"mission_id,omitempty"`
	Symbol    string `json:"symbol,omitempty"`
	Path      string `json:"path,omitempty"`
	StartLine int    `json:"start_line,omitempty"`
	N         int    `json:"n,omitempty"`
	TopK      int    `json:"top_k,omitempty"`
}

// CompileResult holds the compiled Mission and its prefetch manifest.
type CompileResult struct {
	Mission       Mission        `json:"mission"`
	ShardRequests []ShardRequest `json:"shard_requests"`
}

// CompileAA transforms a parsed AAProgram into a CompileResult containing
// a Mission struct and a list of initial shard requests (the "prefetch manifest").
func CompileAA(prog *AAProgram) (*CompileResult, error) {
	missionID := genID()

	mission := Mission{
		MissionID:   missionID,
		Goal:        strings.Join(prog.Dos, "; "),
		BaseRev:     prog.BaseRev,
		Scopes:      prog.Leases,
		LeaseIDs:    []string{},
		Tasks:       prog.Dos,
		TokenBudget: 8000,
		CreatedAt:   nowFunc().UTC().Format(time.RFC3339),
	}

	var shards []ShardRequest
	for _, need := range prog.Needs {
		sr := ShardRequest{
			Args: ShardRequestArgs{MissionID: missionID},
		}
		switch need.Kind {
		case "symdef":
			sr.Command = "PF_SYMDEF"
			sr.Args.Symbol = need.Symbol
		case "callers":
			sr.Command = "PF_CALLERS"
			sr.Args.Symbol = need.Symbol
			if need.N > 0 {
				sr.Args.TopK = need.N
			}
		case "slice":
			sr.Command = "PF_SLICE"
			sr.Args.Path = need.Path
			sr.Args.StartLine = need.Start
			sr.Args.N = need.N
		}
		shards = append(shards, sr)
	}

	return &CompileResult{
		Mission:       mission,
		ShardRequests: shards,
	}, nil
}
