package god

import (
	"encoding/json"
	"fmt"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/genesis-ssmp/genesis/heaven"
)

// ---------------------------------------------------------------------------
// Mock Angel Provider for E2E
// ---------------------------------------------------------------------------

// e2eProvider simulates angel responses with deterministic Edit IR outputs.
type e2eProvider struct {
	responses map[string][]byte // mission_id -> raw response
}

func (p *e2eProvider) Send(pack *MissionPack) ([]byte, error) {
	if resp, ok := p.responses[pack.Mission.MissionID]; ok {
		return resp, nil
	}
	// Default: return a valid no-op response
	return json.Marshal(AngelResponse{
		MissionID:  pack.Mission.MissionID,
		OutputType: "edit_ir",
		EditIR:     &EditIR{Ops: []EditOp{}},
		Manifest: Manifest{
			SymbolsTouched: []string{},
			FilesTouched:   []string{},
		},
	})
}

// makeAngelResponse creates a mock angel response with an add_file op.
func makeAngelResponse(missionID, filePath, content string) []byte {
	resp := AngelResponse{
		MissionID:  missionID,
		OutputType: "edit_ir",
		EditIR: &EditIR{
			Ops: []EditOp{
				{
					Op:         "add_file",
					Path:       filePath,
					AnchorHash: "new_file",
					Content:    content,
				},
			},
		},
		Manifest: Manifest{
			SymbolsTouched: []string{},
			FilesTouched:   []string{filePath},
		},
	}
	data, _ := json.Marshal(resp)
	return data
}

// ---------------------------------------------------------------------------
// E2E Test: Full workflow
// ---------------------------------------------------------------------------

func TestE2EFullWorkflow(t *testing.T) {
	// --- Setup: start a real Heaven server ---
	dataDir := t.TempDir()
	srv, err := heaven.NewServer(dataDir)
	if err != nil {
		t.Fatalf("heaven server init: %v", err)
	}
	ts := httptest.NewServer(srv)
	t.Cleanup(ts.Close)

	client := NewHeavenClient(ts.URL)

	// --- Step 1: Check initial status ---
	status, err := client.GetStatus()
	if err != nil {
		t.Fatalf("initial status: %v", err)
	}
	initialStateRev := status.StateRev

	// --- Step 2: Index fixture repo ---
	fixtureDir, err := filepath.Abs("../fixtures")
	if err != nil {
		t.Fatalf("abs fixtures: %v", err)
	}
	if _, err := os.Stat(filepath.Join(fixtureDir, "sample.go")); os.IsNotExist(err) {
		t.Skipf("fixtures not found at %s", fixtureDir)
	}

	filesIndexed, err := client.IRBuild(fixtureDir)
	if err != nil {
		t.Fatalf("ir build: %v", err)
	}
	if filesIndexed == 0 {
		t.Error("expected at least 1 file indexed")
	}
	t.Logf("Indexed %d files from %s", filesIndexed, fixtureDir)

	// state_rev should have incremented
	status, _ = client.GetStatus()
	if status.StateRev <= initialStateRev {
		t.Error("state_rev should increment after index build")
	}

	// --- Step 3: Plan to create 2+ missions ---
	planner := NewPlanner(client)
	dag, err := planner.Plan("Refactor the Greet function and update tests", fixtureDir)
	if err != nil {
		t.Fatalf("plan: %v", err)
	}

	if len(dag.Nodes) < 2 {
		t.Errorf("expected at least 2 missions, got %d", len(dag.Nodes))
	}
	t.Logf("Created %d missions in plan %s", len(dag.Nodes), dag.PlanID)
	for _, n := range dag.Nodes {
		t.Logf("  mission %s: %s", n.Mission.MissionID[:8], n.Mission.Goal)
	}

	// state_rev should have incremented again (events logged)
	postPlanStatus, _ := client.GetStatus()
	if postPlanStatus.StateRev <= status.StateRev {
		t.Error("state_rev should increment after planning")
	}

	// --- Step 4: Set up metrics + mock provider ---
	metricsAgg := NewMetricsAggregator(client)
	thrashDetector := NewThrashDetector(DefaultThrashConfig(), client)

	// Create a repo working directory for integration
	workDir := t.TempDir()
	// Copy sample.go into work dir for modification
	sampleContent, _ := os.ReadFile(filepath.Join(fixtureDir, "sample.go"))
	os.WriteFile(filepath.Join(workDir, "sample.go"), sampleContent, 0o644)

	// Build mock provider responses for the implementation missions
	mockResponses := make(map[string][]byte)
	for i, node := range dag.Nodes {
		m := node.Mission
		if len(m.Tasks) > 0 && m.Tasks[0] == "analyze" {
			continue // skip analysis mission
		}
		fileName := "generated_" + string(rune('a'+i)) + ".go"
		content := "package sample\n\n// Generated by mission " + m.MissionID[:8] + "\nfunc Generated" + string(rune('A'+i)) + "() string { return \"hello\" }\n"
		mockResponses[m.MissionID] = makeAngelResponse(m.MissionID, fileName, content)
	}

	provider := &e2eProvider{responses: mockResponses}
	adapter := NewProviderAdapter(provider)

	// --- Step 5: Execute missions ---
	integrator := NewIntegrator(client)
	var executedMissions int

	for _, node := range dag.Nodes {
		m := node.Mission
		metricsAgg.StartMission(m.MissionID)

		if len(m.Tasks) > 0 && m.Tasks[0] == "analyze" {
			// Analysis mission: just mark complete
			metricsAgg.EndTurn(m.MissionID)
			metricsAgg.CompleteMission(m.MissionID)
			t.Logf("  Completed analysis mission %s", m.MissionID[:8])
			continue
		}

		// Build a prompt pack
		pack := &MissionPack{
			Header:  "Execute mission",
			Mission: m,
			BudgetMeta: BudgetMeta{
				TokenBudget: m.TokenBudget,
				TotalTokens: 100,
			},
		}

		// Send to mock provider
		angelResp, usage, err := adapter.Execute(pack)
		if err != nil {
			t.Fatalf("provider execute for %s: %v", m.MissionID[:8], err)
		}
		metricsAgg.RecordProviderUsage(usage)

		// Acquire file leases for the touched files
		if len(angelResp.Manifest.FilesTouched) > 0 {
			fileScopes := make([]Scope, len(angelResp.Manifest.FilesTouched))
			for j, f := range angelResp.Manifest.FilesTouched {
				fileScopes[j] = Scope{ScopeType: "file", ScopeValue: f}
			}
			client.LeaseAcquire("e2e-owner", m.MissionID, fileScopes)
		}

		// Get current file clocks for validation
		fileClocks := make(map[string]int64)
		if len(angelResp.Manifest.FilesTouched) > 0 {
			clocks, _ := client.FileClockGet(angelResp.Manifest.FilesTouched)
			fileClocks = clocks
		}

		// Integrate
		intResult, err := integrator.Integrate(IntegrateRequest{
			OwnerID:    "e2e-owner",
			RepoRoot:   workDir,
			Response:   angelResp,
			Mission:    m,
			FileClocks: fileClocks,
		})
		if err != nil {
			t.Fatalf("integrate for %s: %v", m.MissionID[:8], err)
		}

		if intResult.Success {
			executedMissions++
			t.Logf("  Integrated mission %s: %d ops, files: %v %v",
				m.MissionID[:8], intResult.OpsApplied,
				intResult.FilesCreated, intResult.FilesModified)
		} else {
			metricsAgg.RecordReject(m.MissionID)
			t.Logf("  Mission %s rejected: %s", m.MissionID[:8], intResult.Error)
		}

		// Check thrash
		metrics := metricsAgg.Get(m.MissionID)
		thrashResult := thrashDetector.Check(metrics)
		if thrashResult.Thrashing {
			t.Logf("  Mission %s THRASHING: %s", m.MissionID[:8], thrashResult.Reason)
		}

		metricsAgg.EndTurn(m.MissionID)
		metricsAgg.CompleteMission(m.MissionID)
	}

	if executedMissions == 0 {
		t.Error("expected at least 1 mission to integrate successfully")
	}

	// --- Step 6: Run verifier ---
	verifier := NewVerifier(client)
	verifier.runCmd = mockRunCmd("PASS\nok  \tpkg\t0.005s\n", 0)

	vResult, err := verifier.Verify(VerifyRequest{
		MissionID: dag.PlanID,
		RepoRoot:  workDir,
		Command:   "echo PASS",
	})
	if err != nil {
		t.Fatalf("verify: %v", err)
	}
	if !vResult.Passed {
		t.Error("expected verification to pass")
	}
	if vResult.BlobID == "" {
		t.Error("expected receipt blob ID")
	}
	if vResult.Receipt.MissionID != dag.PlanID {
		t.Errorf("receipt mission_id = %q, want %q", vResult.Receipt.MissionID, dag.PlanID)
	}
	t.Logf("Verification: passed=%v, blob_id=%s", vResult.Passed, vResult.BlobID)

	// --- Step 7: Gate merge ---
	if err := GateMerge(vResult.Receipt); err != nil {
		t.Fatalf("gate merge should pass: %v", err)
	}

	// --- Step 8: Validate state_rev incremented ---
	finalStatus, err := client.GetStatus()
	if err != nil {
		t.Fatalf("final status: %v", err)
	}
	if finalStatus.StateRev <= postPlanStatus.StateRev {
		t.Error("state_rev should have incremented after integration and verification")
	}
	t.Logf("state_rev: initial=%d, post_plan=%d, final=%d",
		initialStateRev, postPlanStatus.StateRev, finalStatus.StateRev)

	// --- Step 9: Validate events logged ---
	events, err := client.TailEvents(100)
	if err != nil {
		t.Fatalf("tail events: %v", err)
	}
	if len(events) == 0 {
		t.Fatal("expected events to be logged")
	}

	eventTypes := make(map[string]int)
	for _, raw := range events {
		var evt map[string]any
		json.Unmarshal(raw, &evt)
		if evtType, ok := evt["type"].(string); ok {
			eventTypes[evtType]++
		}
	}

	t.Logf("Events logged: %v", eventTypes)

	// Must have mission_created events
	if eventTypes["mission_created"] == 0 {
		t.Error("expected mission_created events")
	}
	// Must have integration events
	if eventTypes["integration_complete"] == 0 {
		t.Error("expected integration_complete events")
	}
	// Must have verification event
	if eventTypes["verification_complete"] == 0 {
		t.Error("expected verification_complete event")
	}
	// Must have metrics snapshots
	if eventTypes["metrics_snapshot"] == 0 {
		t.Error("expected metrics_snapshot events")
	}

	// --- Step 10: Print metrics summary ---
	t.Log("\n--- Mission Metrics Summary ---")
	for _, node := range dag.Nodes {
		summary := metricsAgg.Summary(node.Mission.MissionID)
		for _, line := range strings.Split(summary, "\n") {
			if line != "" {
				t.Logf("  %s", line)
			}
		}
	}
}

// ---------------------------------------------------------------------------
// E2E: Determinism — same inputs → same outputs
// ---------------------------------------------------------------------------

func TestE2EDeterminism(t *testing.T) {
	// Freeze time and IDs for determinism
	origNow := nowFunc
	origID := idFunc
	t.Cleanup(func() { nowFunc = origNow; idFunc = origID })

	runDeterministic := func() (planIDs []string, missionIDs []string, eventCount int) {
		// Reset clock and ID generator for each run
		frozen := time.Date(2025, 1, 1, 0, 0, 0, 0, time.UTC)
		nowFunc = func() time.Time { return frozen }
		counter := 0
		idFunc = func() string {
			counter++
			return fmt.Sprintf("det-%04d", counter)
		}

		dataDir := t.TempDir()
		srv, err := heaven.NewServer(dataDir)
		if err != nil {
			t.Fatalf("heaven server init: %v", err)
		}
		ts := httptest.NewServer(srv)
		defer ts.Close()

		client := NewHeavenClient(ts.URL)

		// Index fixture repo
		fixtureDir, _ := filepath.Abs("../fixtures")
		if _, err := os.Stat(filepath.Join(fixtureDir, "sample.go")); os.IsNotExist(err) {
			t.Skipf("fixtures not found at %s", fixtureDir)
		}
		client.IRBuild(fixtureDir)

		// Plan
		planner := NewPlanner(client)
		dag, err := planner.Plan("Add a helper function", fixtureDir)
		if err != nil {
			t.Fatalf("plan: %v", err)
		}

		planIDs = append(planIDs, dag.PlanID)
		for _, n := range dag.Nodes {
			missionIDs = append(missionIDs, n.Mission.MissionID)
		}

		events, _ := client.TailEvents(1000)
		eventCount = len(events)
		return
	}

	planIDs1, missionIDs1, eventCount1 := runDeterministic()
	planIDs2, missionIDs2, eventCount2 := runDeterministic()

	// Plan IDs must match
	if len(planIDs1) != len(planIDs2) {
		t.Fatalf("plan count mismatch: %d vs %d", len(planIDs1), len(planIDs2))
	}
	for i := range planIDs1 {
		if planIDs1[i] != planIDs2[i] {
			t.Errorf("plan ID[%d] differs: %s vs %s", i, planIDs1[i], planIDs2[i])
		}
	}

	// Mission IDs must match
	if len(missionIDs1) != len(missionIDs2) {
		t.Fatalf("mission count mismatch: %d vs %d", len(missionIDs1), len(missionIDs2))
	}
	for i := range missionIDs1 {
		if missionIDs1[i] != missionIDs2[i] {
			t.Errorf("mission ID[%d] differs: %s vs %s", i, missionIDs1[i], missionIDs2[i])
		}
	}

	// Event counts must match
	if eventCount1 != eventCount2 {
		t.Errorf("event count mismatch: %d vs %d", eventCount1, eventCount2)
	}
}

// ---------------------------------------------------------------------------
// E2E: No repo dump — mission packs respect token budget
// ---------------------------------------------------------------------------

func TestE2ENoRepoDump(t *testing.T) {
	dataDir := t.TempDir()
	srv, err := heaven.NewServer(dataDir)
	if err != nil {
		t.Fatalf("heaven server init: %v", err)
	}
	ts := httptest.NewServer(srv)
	t.Cleanup(ts.Close)

	client := NewHeavenClient(ts.URL)

	// Index fixture repo
	fixtureDir, _ := filepath.Abs("../fixtures")
	if _, err := os.Stat(filepath.Join(fixtureDir, "sample.go")); os.IsNotExist(err) {
		t.Skipf("fixtures not found at %s", fixtureDir)
	}
	client.IRBuild(fixtureDir)

	// Plan
	planner := NewPlanner(client)
	dag, err := planner.Plan("Add a pow operation", fixtureDir)
	if err != nil {
		t.Fatalf("plan: %v", err)
	}

	// Compile packs and verify budget constraints
	pc := NewPromptCompiler(ts.URL + "/pf")

	for _, node := range dag.Nodes {
		m := node.Mission

		// Fetch candidate shards for this mission
		candidates := []CandidateShard{}
		for _, scope := range m.Scopes {
			if scope.ScopeType == "symbol" {
				candidates = append(candidates, CandidateShard{
					Kind:    "symdef",
					BlobID:  "blob-" + scope.ScopeValue,
					Content: []byte(`{"symbol":"` + scope.ScopeValue + `","definition":"func ` + scope.ScopeValue + `() {}"}`),
					Symbol:  scope.ScopeValue,
				})
			}
		}

		pack, err := pc.Compile(m, candidates)
		if err != nil {
			t.Fatalf("compile mission %s: %v", m.MissionID[:8], err)
		}

		// Pack size must not exceed 32KB
		packJSON, _ := json.Marshal(pack)
		if len(packJSON) > 32*1024 {
			t.Errorf("mission %s: pack size %d exceeds 32KB", m.MissionID[:8], len(packJSON))
		}

		// Total tokens must not exceed budget
		if pack.BudgetMeta.TotalTokens > pack.BudgetMeta.TokenBudget {
			t.Errorf("mission %s: total tokens %d exceeds budget %d",
				m.MissionID[:8], pack.BudgetMeta.TotalTokens, pack.BudgetMeta.TokenBudget)
		}

		// No single shard should be > 50% of budget
		halfBudget := m.TokenBudget / 2
		for _, shard := range pack.InlineShards {
			shardTokens := EstimateTokens(shard.Content)
			if shardTokens > halfBudget {
				t.Errorf("mission %s: shard %s (%d tokens) exceeds 50%% of budget (%d)",
					m.MissionID[:8], shard.Kind, shardTokens, m.TokenBudget)
			}
		}

		// No sensitive files in shards
		for _, shard := range pack.InlineShards {
			content := string(shard.Content)
			if strings.Contains(content, ".env") || strings.Contains(content, "credentials.json") {
				t.Errorf("mission %s: shard contains sensitive file reference", m.MissionID[:8])
			}
		}
	}
}

// ---------------------------------------------------------------------------
// E2E: Thrash detection and recovery
// ---------------------------------------------------------------------------

func TestE2EThrashDetectionAndRecovery(t *testing.T) {
	dataDir := t.TempDir()
	srv, err := heaven.NewServer(dataDir)
	if err != nil {
		t.Fatalf("heaven server init: %v", err)
	}
	ts := httptest.NewServer(srv)
	t.Cleanup(ts.Close)

	client := NewHeavenClient(ts.URL)
	metricsAgg := NewMetricsAggregator(client)

	config := DefaultThrashConfig()
	config.MaxRejects = 2
	thrashDetector := NewThrashDetector(config, client)

	// Simulate a mission that gets rejected repeatedly
	missionID := genID()
	metricsAgg.StartMission(missionID)

	// Reject 1
	metricsAgg.RecordReject(missionID)
	metricsAgg.EndTurn(missionID)
	m := metricsAgg.Get(missionID)
	result := thrashDetector.Check(m)
	if result.Thrashing {
		t.Error("should not thrash after 1 reject")
	}

	// Reject 2 — triggers thrash
	metricsAgg.RecordReject(missionID)
	metricsAgg.EndTurn(missionID)
	m = metricsAgg.Get(missionID)
	result = thrashDetector.Check(m)
	if !result.Thrashing {
		t.Fatal("should thrash after 2 rejects")
	}
	t.Logf("Thrash detected: %s", result.Reason)

	// Set up oracle for recovery with a proper OracleResponse
	oracleRespJSON, _ := json.Marshal(OracleResponse{
		UpdatedDAG: &MissionDAG{
			PlanID:   "recovery-plan",
			TaskDesc: "Recovered from thrash",
			Nodes: []DAGNode{
				{Mission: Mission{MissionID: "recovery-m1", Goal: "Fix root cause", BaseRev: "HEAD", Tasks: []string{"fix"}, TokenBudget: 8000, CreatedAt: time.Now().UTC().Format(time.RFC3339)}},
			},
			CreatedAt: time.Now().UTC().Format(time.RFC3339),
		},
		LeasesPlan:       []Scope{{ScopeType: "file", ScopeValue: "sample.go"}},
		RiskHotspots:     []string{"sample.go"},
		RecommendedTests: []string{"go test ./..."},
	})
	oracleProvider := &e2eProvider{responses: map[string][]byte{}}
	// Override Send to return oracle response for any pack
	oracle := NewOracle(OracleConfig{Enabled: true, Provider: &mockOracleProvider{response: oracleRespJSON}}, client)

	oracleResp, err := oracle.EscalateOnThrash(missionID, m, "spec-blob-e2e")
	if err != nil {
		t.Fatalf("oracle escalate: %v", err)
	}
	if oracleResp == nil {
		t.Fatal("expected oracle response for thrashing mission")
	}
	t.Logf("Oracle returned replacement plan: %s with %d nodes", oracleResp.UpdatedDAG.PlanID, len(oracleResp.UpdatedDAG.Nodes))

	_ = oracleProvider // provider prepared for oracle

	// Verify events trail
	events, err := client.TailEvents(100)
	if err != nil {
		t.Fatalf("tail events: %v", err)
	}

	hasThrash := false
	hasMetrics := false
	for _, raw := range events {
		var evt map[string]any
		json.Unmarshal(raw, &evt)
		switch evt["type"] {
		case "mission_thrashing":
			hasThrash = true
		case "metrics_snapshot":
			hasMetrics = true
		}
	}
	if !hasThrash {
		t.Error("expected mission_thrashing event in log")
	}

	// Complete the mission and check final metrics
	metricsAgg.CompleteMission(missionID)
	if !hasMetrics {
		// Check again after completion
		events, _ = client.TailEvents(100)
		for _, raw := range events {
			var evt map[string]any
			json.Unmarshal(raw, &evt)
			if evt["type"] == "metrics_snapshot" {
				hasMetrics = true
			}
		}
	}
	if !hasMetrics {
		t.Error("expected metrics_snapshot event after completion")
	}

	t.Logf("Final metrics:\n%s", metricsAgg.Summary(missionID))
}

// ---------------------------------------------------------------------------
// E2E: Receipt and gate merge
// ---------------------------------------------------------------------------

func TestE2EReceiptAndGate(t *testing.T) {
	dataDir := t.TempDir()
	srv, err := heaven.NewServer(dataDir)
	if err != nil {
		t.Fatalf("heaven server init: %v", err)
	}
	ts := httptest.NewServer(srv)
	t.Cleanup(ts.Close)

	client := NewHeavenClient(ts.URL)
	verifier := NewVerifier(client)

	// Pass case
	verifier.runCmd = mockRunCmd("all tests passed\n", 0)
	passResult, err := verifier.Verify(VerifyRequest{
		MissionID: "e2e-pass",
		RepoRoot:  t.TempDir(),
		Command:   "echo pass",
	})
	if err != nil {
		t.Fatalf("verify pass: %v", err)
	}
	if !passResult.Passed {
		t.Error("expected pass")
	}
	if err := GateMerge(passResult.Receipt); err != nil {
		t.Errorf("gate should pass: %v", err)
	}

	// Fail case
	verifier.runCmd = mockRunCmd("FAIL\n", 1)
	failResult, err := verifier.Verify(VerifyRequest{
		MissionID: "e2e-fail",
		RepoRoot:  t.TempDir(),
		Command:   "echo fail",
	})
	if err != nil {
		t.Fatalf("verify fail: %v", err)
	}
	if failResult.Passed {
		t.Error("expected fail")
	}
	if err := GateMerge(failResult.Receipt); err == nil {
		t.Error("gate should block failed verification")
	}

	// Verify receipts are stored in Heaven
	if passResult.BlobID == "" {
		t.Error("pass receipt should have blob ID")
	}
	if failResult.BlobID == "" {
		t.Error("fail receipt should have blob ID")
	}

	// Verify receipt timestamps
	for _, r := range []VerifyResult{*passResult, *failResult} {
		if _, err := time.Parse(time.RFC3339, r.Receipt.Timestamp); err != nil {
			t.Errorf("invalid timestamp: %v", err)
		}
		if r.Receipt.EnvHash == "" {
			t.Error("receipt should have env hash")
		}
		if r.Receipt.CommandHash == "" {
			t.Error("receipt should have command hash")
		}
		if r.Receipt.StdoutHash == "" {
			t.Error("receipt should have stdout hash")
		}
	}

	// Check events
	events, _ := client.TailEvents(100)
	verifyEvents := 0
	for _, raw := range events {
		var evt map[string]any
		json.Unmarshal(raw, &evt)
		if evt["type"] == "verification_complete" {
			verifyEvents++
		}
	}
	if verifyEvents != 2 {
		t.Errorf("expected 2 verification_complete events, got %d", verifyEvents)
	}
}

// ---------------------------------------------------------------------------
// E2E: Status endpoint
// ---------------------------------------------------------------------------

func TestE2EStatusAndLogs(t *testing.T) {
	dataDir := t.TempDir()
	srv, err := heaven.NewServer(dataDir)
	if err != nil {
		t.Fatalf("heaven server init: %v", err)
	}
	ts := httptest.NewServer(srv)
	t.Cleanup(ts.Close)

	client := NewHeavenClient(ts.URL)

	// Initial status
	status, err := client.GetStatus()
	if err != nil {
		t.Fatalf("status: %v", err)
	}
	if status.StateRev < 0 {
		t.Errorf("state_rev = %d", status.StateRev)
	}

	// Append some events
	client.AppendEvent(map[string]any{"type": "test_event_1", "data": "hello"})
	client.AppendEvent(map[string]any{"type": "test_event_2", "data": "world"})

	// Check state_rev incremented
	status2, _ := client.GetStatus()
	if status2.StateRev <= status.StateRev {
		t.Error("state_rev should increment after events")
	}

	// Tail events
	events, err := client.TailEvents(10)
	if err != nil {
		t.Fatalf("tail events: %v", err)
	}
	if len(events) < 2 {
		t.Errorf("expected at least 2 events, got %d", len(events))
	}

	// Verify event content
	var lastEvt map[string]any
	json.Unmarshal(events[len(events)-1], &lastEvt)
	if lastEvt["type"] != "test_event_2" {
		t.Errorf("last event type = %v", lastEvt["type"])
	}
}
